# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

master_doc = 'index'

project = 'WebankBlockchain-OpenLedger文档'
copyright = u'© 2021, 版权所有深圳前海微众银行股份有限公司'
author = u'WebankBlockchain-OpenLedger 开发团队'

# The full version, including alpha/beta/rc tags
release = 'v1.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'recommonmark',
    # 'sphinx_markdown_tables',
]

source_suffix = ['.rst', '.md']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
import sphinx_rtd_theme
html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

latex_engine = 'xelatex'

latex_documents = [
  (master_doc, 'WebankBlockchain-OpenLedger-doc.tex', u'WebankBlockchain-OpenLedger Documentation',
   u'WebankBlockchain-OpenLedger开发团队', 'manual'),
]

latex_use_xindy = True
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '12pt',
    'pointsize': '10pt',
    # 'classoptions': ',english',
    'inputenc': '',
    'utf8extra': '',
    'extraclassoptions': 'openany',

    # Additional stuff for the LaTeX preamble.
    'preamble': r'''
\usepackage{xeCJK}
\usepackage{indentfirst}
\setlength{\parindent}{2em}
\setCJKmainfont[BoldFont=SourceHanSansSC-Bold, ItalicFont=SourceHanSansSC-Light]{SourceHanSansSC-Regular}
\setCJKmonofont[Scale=0.9]{SourceHanSansSC-Regular}
\setCJKfamilyfont{SourceHanSansSC-Regular}[BoldFont=SourceHanSansSC-Bold]{SourceHanSansSC-Regular}
\setCJKfamilyfont{sf}[BoldFont=SourceHanSansSC-Bold]{SourceHanSansSC-Regular}
\XeTeXlinebreaklocale "zh"
\XeTeXlinebreakskip = 0pt plus 1pt
\parindent 2em
\definecolor{VerbatimColor}{rgb}{0.95,0.95,0.95}
\setcounter{tocdepth}{3}
\renewcommand\familydefault{\ttdefault}
\renewcommand\CJKfamilydefault{\CJKrmdefault}
''',
    # 'fncychap': r'\usepackage[Bjornstrup]{fncychap}',
    # 'printindex': r'\footnotesize\raggedright\printindex',
}
